name: BanSystem
version: 1.0.0
main: BanSystem\Main
api: [3.0.0, 4.0.0]
author: BajanDoesYT
description: A Minecraft plugin with GUI ban system.
commands:
  bansystem:
    description: Open the Ban System GUI
    usage: /bansystem

