name: ModBanSystem
version: 1.0.0
api: 3.0.0
main: ModBanSystem\Main
commands:
  bansystem:
    description: Manage bans
    usage: '/bansystem <subcommand>'
    permission: bansystem.command
author: BajanDoesYT
