name: ModBanSystem
version: 1.0.0
api: 5.0.0 , 4.0.0 , 5.1.0
main: ModBanSystem\Main
commands:
  bansystem:
    description: Manage bans
    usage: '/bansystem <subcommand>'
    permission: bansystem.command
author: BajanDoesYT
